# NumPy 

NumPy (o Numpy) es una librería muy importante dentro del ecosistema Data Science en Python.  La mayor parte de las librerías en el ecosistema PyData, dependen o se apoyan en NumPy.

Numpy es muy rápido (usa librerías C).

## Instalación

**Puesto que la instalación de Python se ha ejecutado a través de Anaconda, Numpy ya viene instalado.  Los siguientes pasos nos ayudarían a instalar Numpy en caso de no tenerlo instalado.  A través de un terminal ejecutar:**
    
    conda install numpy
    
**En el caso de no tener instalado Anaconda, consultar [Documentación oficial Numpy's.](https://scipy.org/install.html)**

## Usando NumPy

Una vez instalado NumPy, lo importamos como librería:

In [1]:
import numpy as np

Numpy tiene muchas funciones y opciones.  No podremos cubrir todas ellas, pero nos vamos a centrar en algunos de los aspectos más importantes de Numpy: vectores,arrays (conjunto de datos del mismo tipo), matrices, y generación de números.

# Arrays Numpy (Arreglos)

Los arrays en Numpy son esencialmente vectores y matrices. Los vectores son arrays de una dimensión y las matrices de 2 dimensiones (aunque podemos tener matrices de 1 fila o columna).  Son de tipado **estático** y **homogéneo**.  Son más eficientes en el uso de la memoria.  Las funciones matemáticas complejas y computacionalmente costosas (p.ej: multiplicación de matrices) están implementadas en lenguajes compilados como C o Fortran).

## Creación Arrays en Numpy

### Desde una lista

Podemos generar un array directamente convirtiendo una lista o lista de listas:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incluidos para la generación de Arrays

### arange

Genera un rango de datos a partir de un intervalo definido.

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.arange(10,-1,-2)

array([10,  8,  6,  4,  2,  0])

In [17]:
np.arange(10,-1,-3) 

array([10,  7,  4,  1])

Comparación con **range()**, visto previamente.

In [12]:
a = np.arange(0,11)
b = range(11)
print (type(a))
print (type(b))
print (a)
print (*b)

<class 'numpy.ndarray'>
<class 'range'>
[ 0  1  2  3  4  5  6  7  8  9 10]
0 1 2 3 4 5 6 7 8 9 10


In [20]:
a[-1]

10

In [23]:
b[-1]

10

### Ceros y unos

Generar arrays de unos y ceros.

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((3,3))

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

### linspace

Devuelve números espaciados uniformemente en un intervalo especificado.

In [25]:
np.linspace(0,10,4)  #El intervalo viene definido por el número 4.  En este caso, divide el intervalo [0-10] en 4 partes iguales.

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [26]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Crea una matriz identidad (sólo unos en la diagonal y el resto ceros)

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy tiene muchas maneras de generar arrays con números aleatorios:

### rand
Crea un array con la estructura elegida y lo rellena con datos aleatorios obtenidos a partir de una distribución uniforme.

In [28]:
np.random.rand(2)

array([0.04947911, 0.12865492])

In [29]:
np.random.rand(5,5)

array([[0.81652558, 0.14848998, 0.60370317, 0.53770277, 0.95877575],
       [0.97291819, 0.93698182, 0.05772616, 0.86069987, 0.12580521],
       [0.3862491 , 0.78515645, 0.40821875, 0.05223482, 0.8105865 ],
       [0.19005947, 0.05058053, 0.94757298, 0.50435933, 0.06427273],
       [0.31619941, 0.48046594, 0.81773193, 0.14386363, 0.40181946]])

In [30]:
np.random.rand(5,5)

array([[0.74261924, 0.20604658, 0.01017282, 0.92166044, 0.44609913],
       [0.94289676, 0.90205944, 0.15543702, 0.06822358, 0.29900668],
       [0.22207572, 0.01064995, 0.36857129, 0.77449551, 0.36677587],
       [0.27493724, 0.23380537, 0.8178077 , 0.3471287 , 0.0158859 ],
       [0.99216098, 0.27324099, 0.23519086, 0.3330989 , 0.07594904]])

¿Hemos obtenido todos los mismos resultados? ¿Porqué obtenemos diferentes arrays?
Ello se debe a que no estamos usando la misma 'semilla' para generar los números aleatorios.

In [29]:
np.random.seed(30)
np.random.rand(5,5)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781],
       [0.34666184, 0.99175099, 0.2350579 , 0.58569427, 0.4066901 ],
       [0.13623432, 0.54413629, 0.51817635, 0.76685511, 0.93385014],
       [0.08970338, 0.19577126, 0.99419368, 0.2351805 , 0.23898637],
       [0.62909983, 0.73495258, 0.68834438, 0.03113075, 0.90251384]])

In [43]:
np.random.seed(30)
np.random.rand(5,5)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781],
       [0.34666184, 0.99175099, 0.2350579 , 0.58569427, 0.4066901 ],
       [0.13623432, 0.54413629, 0.51817635, 0.76685511, 0.93385014],
       [0.08970338, 0.19577126, 0.99419368, 0.2351805 , 0.23898637],
       [0.62909983, 0.73495258, 0.68834438, 0.03113075, 0.90251384]])

### randn

Devuelve una muestra (o muestras) de una distribución estándar normal, al contrario que **rand** que es uniforme:


In [30]:
np.random.randn(2)

array([ 0.45579259, -1.7503454 ])

In [42]:
np.random.randn(5,5)

array([[-0.97068713,  1.77030439, -0.42801373,  1.71569932,  0.15935506],
       [ 0.73179664,  0.17293621,  0.78121553, -0.0054139 , -0.0386085 ],
       [-0.69590645, -0.96953075, -1.17688716,  0.34154385, -0.70029204],
       [ 0.91056618, -0.07598921, -0.2688407 , -0.59589176,  0.03269273],
       [-1.58790121,  1.89274748, -0.0329534 ,  1.80558596, -1.05095113]])

### randint
Devuelve enteros aleatorios entre un rango inferior (incluido) y otro superior (no incluido).  El rango inferior, debe ser menor que el rango superior.

In [43]:
np.random.randint(1,100)  # El rango estaría comprendido entre 1 y 99,99999999999999999

78

In [44]:
np.random.randint(1,100,10)  # Con el tercer argumento, nos devuelve 10 números aleatorios.

array([52, 45, 89, 35, 98, 25, 51,  4, 61, 78])

In [5]:
np.random.randint(100,1,10)

ValueError: low >= high

## Atributos y métodos en Arrays


In [45]:
np.random.seed(30)
arr = np.arange(30)
ranarr = np.random.randint(0,50,10) # El método randint devuelve un entero del rango especificado.

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
ranarr

array([37, 37, 45, 45, 12, 23,  2, 17, 46,  3])

## Reshape
Devuelve un array que contiene los mismos datos, pero con una distribución diferente.

In [20]:
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [21]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [22]:
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### max,min,argmax,argmin

Métodos prácticos para obtener los valores máximos y mínimos, o para encontrar su índice a través de argmin o argmax

In [48]:
ranarr

array([37, 37, 45, 45, 12, 23,  2, 17, 46,  3])

In [49]:
ranarr.max()

46

In [50]:
ranarr.argmax()

8

In [51]:
ranarr.min()

2

In [52]:
ranarr.argmin()

6

In [53]:
arr1 = np.arange(30).reshape(6,5)

In [54]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [56]:
arr1.argmax()

29

## Shape

Shape es un atributo que devuelve una tupla con las dimensiones del array

In [57]:
# Vector
arr.shape

(30,)

In [59]:
# Atención a los 2 sets de corchetes
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

En el primer caso tenemos un array unidimensional con 30 elementos,  mientras que en el segundo caso tenemos un array de 2 dimensiones(1x30, 1 fila)

In [60]:
print(arr.ndim)
print(arr.reshape(1,30).ndim)

1
2


In [61]:
arr.reshape(1,30).shape

(1, 30)

In [62]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [63]:
arr.reshape(30,1).shape

(30, 1)

In [64]:
arr.ndim

1

### dtype

El método dtype devuelve el tipo de dato en el array.

In [65]:
arr.dtype

dtype('int32')

In [67]:
np.ones((5,5)).dtype

dtype('float64')

# NumPy Indexación y Selección 

Veremos cómo seleccionar elementos o grupos de elementos de un array.

In [71]:
#Generamos un array de muestra
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexación y selección a través de "Corchetes"
Es la manera más sencilla de seleccionar uno o varios elementos de un array.  Se parece mucho a las listas de python:

In [73]:
#Devuelve el valor existente en la posición 9 del array
arr[9]

9

In [74]:
#Devuelve los valores existentes en un rango
arr[1:5]

array([1, 2, 3, 4])

In [75]:
#Devuelve los valores existentes en un rango
arr[0:5]

array([0, 1, 2, 3, 4])

## Difusión

Los arrays en numpy tienen la propiedad de "difusión":

In [9]:
#Asignar un valor a través de un rango en el índice (difusión)
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [76]:
# Resetear el array (vemos en un momento porqué)
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
#Extraemos una "porción" de los datos
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [84]:
a = arr[0:6].copy()


In [85]:
a[:] = 100
a

array([100, 100, 100, 100, 100, 100])

In [78]:
#Cambiamos de una vez los valores existentes en la "porción" extraída
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [86]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

¿Qué ha pasado con el array original?.  

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

slice_of_arr es un alias de arr (ocupan el mismo espacio de memoria) y cualquier cambio en slice_of_arr se refleja en arr

In [43]:
#Para generar una copia del array, debemos hacerlo explícitamente.
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_copy[:]=100
print (arr_copy)
print (arr)

[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


## Indexado de matrices 2D
El formato general es **arr_2d[filas][columnas]** o **arr_2d[filas,columnas]**. La notación a través de comas, suele ser más clara.

In [87]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
#Indexado de fila 1.  Ojo, la fila 1 es la segunda fila del array.  La primera fila es la 0.
arr_2d[1]


array([20, 25, 30])

In [89]:
# Extrayendo un elemento individual
arr_2d[1][0]

20

In [90]:
# Extrayendo un elemento individual
arr_2d[1,0]

20

In [49]:
# Extracción de elementos en un array 2D array.
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [20]:
#Extracción de la última fila
arr_2d[2]

array([35, 40, 45])

In [50]:
#Otra forma de extraer la última fila
arr_2d[2,:]

array([35, 40, 45])

In [91]:
#Generamos un nuevo array de ejemplo
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
#Extraemos las filas 2 y 3 y las columnas 4 y 5.  Recordad que la primera fila y columna es la 0
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

Podemos verlo gráficamente


<img src='./logo/numpy_indexing.png' />

## Selección de elementos en un array


In [93]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
#Devuelve un lógico con los elementos que cumplen o no la condición a evaluar.
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [95]:
bool_arr = arr>4
#filtro = (arr > 4) | (arr<6)
#arr[filtro]

In [96]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [82]:
#Podemos usar el lógico creado, para seleccionar los elementos que cumplen la condición en el array
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [83]:
#De manera directa
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Operaciones matemáticas

In [98]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
#Suma de elementos de un array
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
#Multiplicación
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [101]:
#Sustracción
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
# Mensaje de advertencia de división entre 0.  No es un error.  Reemplaza la advertencia por nan.  0/0 = nan
arr = np.arange(0,11)
arr/arr

C:\Users\german\AppData\Local\Temp\ipykernel_19896\963120252.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [103]:
# Nos muestra otra advertencia, pero no error.  1/0 = infinito
1/arr

C:\Users\german\AppData\Local\Temp\ipykernel_19896\3494808330.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [104]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr[2] = arr[2]**3
arr

array([ 0,  1,  8,  3,  4,  5,  6,  7,  8,  9, 10])

## Funciones universales en arrays

El listado completo de funciones disponibles en numpy puede consultarse aquí: http://docs.scipy.org/doc/numpy/reference/ufuncs.html)
Vemos algunos ejemplos:

In [15]:
#Raíces cuadradas
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
#Exponenciales (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.max(arr) #Se obtiene el mismo resultado a través de arr.max()

10

In [18]:
np.sin(arr) #Cálculo del seno

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [106]:
np.log(arr) #Cálculo del logaritmo

C:\Users\german\AppData\Local\Temp\ipykernel_19896\3182160363.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #Cálculo del logaritmo


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [107]:
np.log2(arr) #Cálculo del logaritmo en base 2

C:\Users\german\AppData\Local\Temp\ipykernel_19896\1481209007.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr) #Cálculo del logaritmo en base 2


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ,
       3.32192809])